In [9]:
#include("../../code/julia/hdfeos_convert.jl")
include("../../code/julia/hdf5 tree.jl")
include("../../code/julia/HDF5filesDict.jl")
include("../../code/julia/printHDF.jl")
include("../../code/julia/drawTree.jl")
closeall = HDF5fd.closeall

closeall (generic function with 1 method)

In [17]:
include("../../code/julia/hdfeos.jl")

Main.hdfeos

In [6]:
include("../../code/julia/faux.jl")

Main.faux

In [10]:
openfiles = HDF5fd.filesDict()


Main.HDF5fd.filesDict(Dict{Any,Any}(), 0)

* https://github.com/lbusett/prismaread/blob/master/R/pr_convert.R

In [18]:
using SparseArrays
in_file="data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5"
file = HDF5fd.open(openfiles,in_file,"r")

vnir_mat = faux.getData(file, "//KDP_AUX/Cw_Vnir_Matrix")
@show count(x->x==0, vnir_mat)
#vnir_mat = sparse(vnir_mat)
vnir_mat


count((x->begin
            #= In[18]:6 =#
            x == 0
        end), vnir_mat) = 193000


256×1000 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0

In [15]:
closeall(openfiles)

chiuso 3 file


In [13]:
a=[1,2,3,4,5]
b=[6,7,8,9]
c=[a...,b...]

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [16]:
c=vcat(a,b)

9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [3]:
function tryIf(x)
    if x in [1,2,3,"asd",false]
        println("$x ok")
        else 
        println("$x non ok")
    end
    
end

tryIf (generic function with 1 method)

In [4]:
x = "ciao"
tryIf(1)
tryIf("asd")
tryIf("kmkgnmg")

1 ok
asd ok
kmkgnmg non ok


In [27]:
using CSV
using DataFrames
mkpath("downloads/")
download("https://github.com/sfacca/stage-Machine-learning/raw/master/extdata/md_indexes_list.txt","downloads/indexes_list.txt")
index_list = CSV.read("downloads/indexes_list.txt")

select!(index_list, Not(:id))
names(index_list)

5-element Array{String,1}:
 "Name"
 "Description"
 "Formula"
 "Sensitivity"
 "Reference"

In [41]:
index_list[:Formula]

132-element Array{String,1}:
 "1 / R550 - 1 / R700"
 "R450 / R550"
 "R450 / R690"
 "0.5*(R2015 + R2195) - R2106"
 "(R675 * R690) / R683 ^ 2"
 "R760 / R700 - 1"
 "1 / R510 - 1 / R550"
 "1/R515 - 1/R550"
 "1 / R510 - 1 / R700"
 "1/R515 - 1/R770"
 "(1/R515 - 1/R550) * R770"
 "(1/R515 - 1/R700) * R770"
 "R695 / R420"
 ⋮
 "3 * ((R750 - R705) - 0.2 * (R750 - R550)*(R750/R705))"
 "(3 * ((R750 - R705) - 0.2 * (R750 - R550)*(R750/R705))) / ((1 + 0.16) * (R750 - R705) / (R750 + R705 + 0.16))"
 "0"
 "0.5 * (120 * (R750 - R550) - 200 * (R670 - R550))"
 "R740/R720"
 "(R734 - R747)/(R715 + R726)"
 "(R734 - R747)/(R715 + R720)"
 "R750 / R710"
 "R600 / R700"
 "R600 / R700"
 "R600 / R700"
 "R600 / R700"

In [179]:
using CSV
using DataFrames
using LinearAlgebra
using DataFramesMeta
#=mkpath("downloads")
download("https://github.com/sfacca/stage-Machine-learning/raw/master/extdata/md_indexes_list.txt","downloads/indexes_list.txt")
=#
index_list = CSV.read("downloads/indexes_list.txt")
select!(index_list, Not(:id))

av_indexes= select(index_list, [:Name,:Formula])
indexes = ["ARI","BGI","BRI"]
sel_indexes = filter(row -> row.Name ∈ indexes, av_indexes)
av_indexes


132×2 DataFrame. Omitted printing of 1 columns
│ Row │ Name          │
│     │ String        │
├─────┼───────────────┤
│ 1   │ ARI           │
│ 2   │ BGI           │
│ 3   │ BRI           │
│ 4   │ CAI           │
│ 5   │ CI            │
│ 6   │ CI2           │
│ 7   │ CRI           │
│ 8   │ CRI1          │
│ 9   │ CRI2          │
│ 10  │ CRI2          │
⋮
│ 122 │ TCARI2/OSAVI2 │
│ 123 │ TGI           │
│ 124 │ TVI           │
│ 125 │ VOG1          │
│ 126 │ VOG2          │
│ 127 │ VOG3          │
│ 128 │ ZTM           │
│ 129 │ myindex       │
│ 130 │ 009066L       │
│ 131 │ 009449D       │
│ 132 │ 008530N       │

In [202]:
# get additional metadata
    sunzen  = hdfeos.getAttr(file, "Sun_zenith_angle")
    sunaz  = hdfeos.getAttr(file, "Sun_azimuth_angle")
    acqtime  = hdfeos.getAttr(file, "Product_StartTime")

ang_df = DataFrame(date = acqtime),sunzen = sunzen,sunaz = sunaz)
CSV.write("out/ang_df.ang",ang_df,delim=' ',quotechar='"',quotestrings=true)

LoadError: SystemError: opening file "C:\\Users\\IAM~1\\AppData\\Local\\Tempout/ang_df.ang": No such file or directory

In [201]:
string("asd","fgh","_asd")

"asdfgh_asd"

In [141]:
function extractWvl(str::String)#prende stringa, ritorna array di numeri
  currnum = 0
  res::Array{Int,1} = []
  intc = ['1','2','3','4','5','6','7','8','9','0']
  afterR = false
  for char in str
    if afterR
      if char in intc
        currnum = currnum*10
        currnum = currnum + parse(Int,char)             
                
      else
        push!(res,currnum)
        currnum=0
        afterR = false
      end    
    end
    if char == 'R'
      afterR = true
    end
  end
  push!(res,currnum)  
  res
end

extractWvl (generic function with 1 method)

In [142]:
req_wls = sort(unique(vcat(extractWvl.(av_indexes[:Formula])...)))

92-element Array{Int64,1}:
    0
  415
  420
  430
  435
  440
  445
  450
  470
  475
  500
  510
  513
    ⋮
 1928
 2015
 2090
 2106
 2133
 2195
 2209
 2210
 2218
 2225
 2280
 2683

In [234]:
wl_vnir = rand(Float64,66)
#1 prendiamo elem req_wls >= maximum(wl_vnir)
sel_vnir = filter(item -> item <= maximum(wl_vnir) && item != 0,req_wls)

Int64[]

In [152]:
myArr = [1,4,5,2,0]
minimum(filter(item -> item !=0,myArr))

1

In [176]:
a = [6,6,9,12,4,2,6]
b= [9,87,6,87,33]
x = unique(sort(a))


5-element Array{Int64,1}:
  2
  4
  6
  9
 12

In [177]:
y = unique(sort(b))

4-element Array{Int64,1}:
  6
  9
 33
 87

In [178]:
checkCommon(usa,usb)

true

In [203]:
using ArchGDAL

┌ Info: Precompiling ArchGDAL [c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3]
└ @ Base loading.jl:1278


In [204]:
wl_vnir

4-element Array{Int64,1}:
   22
   15
  996
 1000

In [211]:
x = [1,2,3]
y= 2
@show z = x.-y
@show za = abs.(x.-y)


z = x .- y = [-1, 0, 1]
za = abs.(x .- y) = [1, 0, 1]


3-element Array{Int64,1}:
 1
 0
 1

In [229]:
function closestWvl(wvl::Array{Int64,1},x::Int64)
  y = abs.(wvl.-x)
  #lapply(selbands_vnir, FUN = function(x) which.min(abs(wl_vnir - x))))
  minimum(abs.(wvl.-x))
end
function closestWvlFun(wvl::Array{Int64,1})
  (x)->(minimum(abs.(wvl.-x)))
end

closestWvlFun (generic function with 1 method)

In [230]:
wvl = [4,3,6,1,-5,1,2,5,6,1]
x = [5,-8,4,1,4,7,8]
closestWvlFun(wvl).(x)

7-element Array{Int64,1}:
 0
 3
 0
 0
 0
 1
 2

In [238]:
wl_vnir[5]=0
wl_vnir[12]=0

seqbands_vnir = [1:66...]
  for i in 1:66
    if wl_vnir[i]==0
      seqbands_vnir[i]=0      
    end
  end
seqbands_vnir = filter(x->x!=0,seqbands_vnir)

64-element Array{Int64,1}:
  1
  2
  3
  4
  6
  7
  8
  9
 10
 11
 13
 14
 15
  ⋮
 55
 56
 57
 58
 59
 60
 61
 62
 63
 64
 65
 66

In [236]:
seqbands_vnir = [1:66]

1-element Array{UnitRange{Int64},1}:
 1:66

In [239]:
wl_vnir = wl_vnir[seqbands_vnir]

64-element Array{Float64,1}:
 0.31389783015988226
 0.9780051176715132
 0.7314546886905584
 0.7737076983924149
 0.5595092474008283
 0.6168637817063221
 0.4497328202445632
 0.5049079094583413
 0.24034062038311466
 0.008912052209757881
 0.5687309419046183
 0.755433700549019
 0.25222311499937056
 ⋮
 0.07091653265743392
 0.5991900796453336
 0.3995412014357924
 0.8524441395956297
 0.5929465621765531
 0.22614649147622456
 0.43785731465921507
 0.3880152749585053
 0.45006544454605346
 0.17590459833502692
 0.560132104627866
 0.979478647374749

*http://www.johnmyleswhite.com/notebook/2012/04/09/comparing-julia-and-rs-vocabularies/

In [30]:
using DataFrames
c = [1,2,3]
b=[4,56,6]
d=DataFrame("parola parola"=c,"ta ta"= b)

LoadError: syntax: invalid keyword argument name ""parola parola"" around In[30]:4

In [31]:
?round

search: round rounding RoundUp RoundDown RoundToZero RoundingMode RoundNearest



```
round(z::Complex[, RoundingModeReal, [RoundingModeImaginary]])
round(z::Complex[, RoundingModeReal, [RoundingModeImaginary]]; digits=, base=10)
round(z::Complex[, RoundingModeReal, [RoundingModeImaginary]]; sigdigits=, base=10)
```

Return the nearest integral value of the same type as the complex-valued `z` to `z`, breaking ties using the specified [`RoundingMode`](@ref)s. The first [`RoundingMode`](@ref) is used for rounding the real components while the second is used for rounding the imaginary components.

# Example

```jldoctest
julia> round(3.14 + 4.5im)
3.0 + 4.0im
```

---

```
round([T,] x, [r::RoundingMode])
round(x, [r::RoundingMode]; digits::Integer=0, base = 10)
round(x, [r::RoundingMode]; sigdigits::Integer, base = 10)
```

Rounds the number `x`.

Without keyword arguments, `x` is rounded to an integer value, returning a value of type `T`, or of the same type of `x` if no `T` is provided. An [`InexactError`](@ref) will be thrown if the value is not representable by `T`, similar to [`convert`](@ref).

If the `digits` keyword argument is provided, it rounds to the specified number of digits after the decimal place (or before if negative), in base `base`.

If the `sigdigits` keyword argument is provided, it rounds to the specified number of significant digits, in base `base`.

The [`RoundingMode`](@ref) `r` controls the direction of the rounding; the default is [`RoundNearest`](@ref), which rounds to the nearest integer, with ties (fractional values of 0.5) being rounded to the nearest even integer. Note that `round` may give incorrect results if the global rounding mode is changed (see [`rounding`](@ref)).

# Examples

```jldoctest
julia> round(1.7)
2.0

julia> round(Int, 1.7)
2

julia> round(1.5)
2.0

julia> round(2.5)
2.0

julia> round(pi; digits=2)
3.14

julia> round(pi; digits=3, base=2)
3.125

julia> round(123.456; sigdigits=2)
120.0

julia> round(357.913; sigdigits=4, base=2)
352.0
```

!!! note
    Rounding to specified digits in bases other than 2 can be inexact when operating on binary floating point numbers. For example, the [`Float64`](@ref) value represented by `1.15` is actually *less* than 1.15, yet will be rounded to 1.2.

    # Examples

    ```jldoctest; setup = :(using Printf)
    julia> x = 1.15
    1.15

    julia> @sprintf "%.20f" x
    "1.14999999999999991118"

    julia> x < 115//100
    true

    julia> round(x, digits=1)
    1.2
    ```


# Extensions

To extend `round` to new numeric types, it is typically sufficient to define `Base.round(x::NewType, r::RoundingMode)`.

---

```
round(dt::TimeType, p::Period, [r::RoundingMode]) -> TimeType
```

Return the `Date` or `DateTime` nearest to `dt` at resolution `p`. By default (`RoundNearestTiesUp`), ties (e.g., rounding 9:30 to the nearest hour) will be rounded up.

For convenience, `p` may be a type instead of a value: `round(dt, Dates.Hour)` is a shortcut for `round(dt, Dates.Hour(1))`.

```jldoctest
julia> round(Date(1985, 8, 16), Dates.Month)
1985-08-01

julia> round(DateTime(2013, 2, 13, 0, 31, 20), Dates.Minute(15))
2013-02-13T00:30:00

julia> round(DateTime(2016, 8, 6, 12, 0, 0), Dates.Day)
2016-08-07T00:00:00
```

Valid rounding modes for `round(::TimeType, ::Period, ::RoundingMode)` are `RoundNearestTiesUp` (default), `RoundDown` (`floor`), and `RoundUp` (`ceil`).

---

```
round(x::Period, precision::T, [r::RoundingMode]) where T <: Union{TimePeriod, Week, Day} -> T
```

Round `x` to the nearest multiple of `precision`. If `x` and `precision` are different subtypes of `Period`, the return value will have the same type as `precision`. By default (`RoundNearestTiesUp`), ties (e.g., rounding 90 minutes to the nearest hour) will be rounded up.

For convenience, `precision` may be a type instead of a value: `round(x, Dates.Hour)` is a shortcut for `round(x, Dates.Hour(1))`.

```jldoctest
julia> round(Dates.Day(16), Dates.Week)
2 weeks

julia> round(Dates.Minute(44), Dates.Minute(15))
45 minutes

julia> round(Dates.Hour(36), Dates.Day)
2 days
```

Valid rounding modes for `round(::Period, ::T, ::RoundingMode)` are `RoundNearestTiesUp` (default), `RoundDown` (`floor`), and `RoundUp` (`ceil`).

Rounding to a `precision` of `Month`s or `Year`s is not supported, as these `Period`s are of inconsistent length.


In [37]:
c = [0.1234567,1.123456789,2.1234567890]
round.(c,digits=3)

3-element Array{Float64,1}:
 0.123
 1.123
 2.123

In [40]:
c=[12345,123456]
round.(c/1000000,digits=5)

2-element Array{Float64,1}:
 0.01234
 0.12346

In [46]:
df = DataFrame(asd=[1,2],bcd=[3,4])
rename!(df,["as d","dd a"])

2×2 DataFrame
│ Row │ as d  │ dd a  │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
│ 2   │ 2     │ 4     │

In [45]:
?names!

search: names! names fieldnames propertynames



No documentation found.

`DataFrames.names!` is a `Function`.

```
# 2 methods for generic function "names!":
[1] names!(x::DataFrames.Index, nms::Array{Symbol,1}; makeunique) in DataFrames at deprecated.jl:70
[2] names!(df::AbstractDataFrame, vals::Array{Symbol,1}; makeunique) in DataFrames at deprecated.jl:70
```


In [47]:
?CSV.write

```
CSV.write(file, table; kwargs...) => file
table |> CSV.write(file; kwargs...) => file
```

Write a [Tables.jl interface input](https://github.com/JuliaData/Tables.jl) to a csv file, given as an `IO` argument or `String`/FilePaths.jl type representing the file name to write to. Alternatively, `CSV.RowWriter` creates a row iterator, producing a csv-formatted string for each row in an input table.

Supported keyword arguments include:

  * `delim::Union{Char, String}=','`: a character or string to print out as the file's delimiter
  * `quotechar::Char='"'`: ascii character to use for quoting text fields that may contain delimiters or newlines
  * `openquotechar::Char`: instead of `quotechar`, use `openquotechar` and `closequotechar` to support different starting and ending quote characters
  * `escapechar::Char='"'`: ascii character used to escape quote characters in a text field
  * `missingstring::String=""`: string to print for `missing` values
  * `dateformat=Dates.default_format(T)`: the date format string to use for printing out `Date` & `DateTime` columns
  * `append=false`: whether to append writing to an existing file/IO, if `true`, it will not write column names by default
  * `writeheader=!append`: whether to write an initial row of delimited column names, not written by default if appending
  * `header`: pass a list of column names (Symbols or Strings) to use instead of the column names of the input table
  * `newline='\n'`: character or string to use to separate rows (lines in the csv file)
  * `quotestrings=false`: whether to force all strings to be quoted or not
  * `decimal='.'`: character to use as the decimal point when writing floating point numbers
  * `transform=(col,val)->val`: a function that is applied to every cell e.g. we can transform all `nothing` values to `missing` using `(col, val) -> something(val, missing)`
  * `bom=false`: whether to write a UTF-8 BOM header (0xEF 0xBB 0xBF) or not


In [50]:
using HDF5
HDF5.exists(file,"//KDP_AUX/Cw_Vnir_Matrix")

true

In [51]:
getAttr(file, "Start_index_EO_VNIR")

HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5A.c line 425 in H5Aopen(): unable to load attribute info from object header for attribute: 'Start_index_EO_VNIR'
    major: Attribute
    minor: Can't open object
  #001: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Aint.c line 433 in H5A__open(): unable to load attribute info from object header for attribute: 'Start_index_EO_VNIR'
    major: Attribute
    minor: Can't open object
  #002: E:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.10.5/src/H5Oattribute.c line 515 in H5O__attr_open_by_name(): can't locate attribute: 'Start_index_EO_VNIR'
    major: Attribute
    minor: Object not found


LoadError: Error opening attribute //Start_index_EO_VNIR

In [55]:
function getAttr2(file, name::String)    
    read(attrs(file), name)
end

getAttr2 (generic function with 1 method)

In [4]:
x = "ciao"
if !isnothing(x)
    println("ok")
end

ok


In [24]:
 A = rand([0, 1], 25, 25)
ordA = [1,3,4,5,6,2]


6-element Array{Int64,1}:
 1
 3
 4
 5
 6
 2

In [25]:
B = A[4:10,:]

7×25 Array{Int64,2}:
 1  0  0  0  0  0  0  1  1  0  1  0  1  0  0  1  1  0  0  0  1  1  0  0  0
 1  1  0  0  1  1  1  0  0  1  1  0  1  1  0  1  0  0  0  1  0  0  0  1  1
 0  1  1  0  0  0  1  1  1  1  1  0  0  1  0  1  1  1  1  0  0  1  0  0  0
 0  1  0  1  0  0  0  1  1  1  1  1  0  1  0  0  0  1  1  1  1  0  0  0  0
 1  0  0  1  1  0  0  1  0  0  0  1  1  0  1  1  0  0  0  1  1  0  0  1  0
 0  1  1  0  1  0  0  1  0  0  0  0  0  1  1  1  1  0  0  1  1  0  1  1  1
 1  1  0  1  0  1  0  0  0  0  1  0  0  1  1  0  0  0  1  0  1  1  1  1  0

In [27]:
B[ordA,:]

6×25 Array{Int64,2}:
 1  0  0  0  0  0  0  1  1  0  1  0  1  0  0  1  1  0  0  0  1  1  0  0  0
 0  1  1  0  0  0  1  1  1  1  1  0  0  1  0  1  1  1  1  0  0  1  0  0  0
 0  1  0  1  0  0  0  1  1  1  1  1  0  1  0  0  0  1  1  1  1  0  0  0  0
 1  0  0  1  1  0  0  1  0  0  0  1  1  0  1  1  0  0  0  1  1  0  0  1  0
 0  1  1  0  1  0  0  1  0  0  0  0  0  1  1  1  1  0  0  1  1  0  1  1  1
 1  1  0  0  1  1  1  0  0  1  1  0  1  1  0  1  0  0  0  1  0  0  0  1  1

In [74]:
x = 7^2
a = [1:x...]

49-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 38
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49

In [75]:
mA = reshape(a,7,7)


7×7 Array{Int64,2}:
 1   8  15  22  29  36  43
 2   9  16  23  30  37  44
 3  10  17  24  31  38  45
 4  11  18  25  32  39  46
 5  12  19  26  33  40  47
 6  13  20  27  34  41  48
 7  14  21  28  35  42  49

In [76]:
mA = mA[2:4,:]

3×7 Array{Int64,2}:
 2   9  16  23  30  37  44
 3  10  17  24  31  38  45
 4  11  18  25  32  39  46

In [77]:
tA = mA[:,mA[1,:].>15]

3×5 Array{Int64,2}:
 16  23  30  37  44
 17  24  31  38  45
 18  25  32  39  46

In [68]:
ordA =mA[:,ord]

3×3 Array{Int64,2}:
 6  3  0
 7  4  1
 8  5  2

In [69]:
ordA[2,2]=0
ordA

3×3 Array{Int64,2}:
 6  3  0
 7  0  1
 8  5  2

In [70]:
ordA = ordA[:,(ordA[1,:] .!=0)]

3×2 Array{Int64,2}:
 6  3
 7  0
 8  5

In [53]:
vnir_start = 3
vnir_stop = 45
swir_start = 8
swir_stop = 47

vnir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_wl_mat = vnir_wl_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_wl_mat = vnir_wl_mat[:,order_vnir]#ordino righe secondo order_vnir
vnir_wl_mat = vnir_wl_mat[:,(vnir_wl_mat[1,:].!=0)]#tolgo colonne che inzian con 0
#stessa cosa per vnir fwhm
vnir_fwhm_mat = faux.getData(file, "KDP_AUX/Fwhm_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_fwhm_mat = vnir_fwhm_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_fwhm_mat = vnir_fwhm_mat[:,order_vnir]#ordino colonne secondo order_vnir
vnir_fwhm_mat = vnir_fwhm_mat[:,(vnir_fwhm_mat[1,:].!=0)]#tolgo colonne con i dove [1,i]==0
#stessa cosa per swir
swir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Swir_Matrix")
swir_wl_mat = swir_wl_mat[swir_start:swir_stop,:]
#swir_wl_mat = swir_wl_mat[:,order_swir]
swir_wl_mat = swir_wl_mat[:,(swir_wl_mat[1,:].!=0)]
swir_fwhm_mat = faux.getData(file, "//KDP_AUX/Fwhm_Swir_Matrix")
swir_fwhm_mat = swir_fwhm_mat[swir_start:swir_stop,:]
#swir_fwhm_mat = swir_fwhm_mat[:,order_swir]
swir_fwhm_mat = swir_fwhm_mat[:,(swir_fwhm_mat[1,:].!=0)]

40×0 Array{Float32,2}

In [49]:
swir_fwhm_mat

6×0 Array{Float32,2}

In [78]:
ordA

3×2 Array{Int64,2}:
 6  3
 7  0
 8  5

In [79]:
mA

3×7 Array{Int64,2}:
 2   9  16  23  30  37  44
 3  10  17  24  31  38  45
 4  11  18  25  32  39  46

In [80]:
[ordA mA]

3×9 Array{Int64,2}:
 6  3  2   9  16  23  30  37  44
 7  0  3  10  17  24  31  38  45
 8  5  4  11  18  25  32  39  46

In [82]:
length(mA)

21

In [83]:
typeof(mA)

Array{Int64,2}

In [85]:
length(mA[1,:])

7