In [42]:
include("../../code/julia/hdf5 tree.jl")
include("../../code/julia/printHDF.jl")
include("../../code/julia/drawTree.jl")

Main.drawTree

In [43]:
#include("../../code/julia/hdfeos_convert.jl")
include("../../code/julia/HDF5filesDict.jl")
include("../../code/julia/eos_create.jl")
closeall = HDF5fd.closeall

closeall (generic function with 1 method)

In [ ]:
using BenchmarkTools

In [44]:
include("../../code/julia/hdfeos.jl")

Main.hdfeos

In [45]:
include("../../code/julia/faux.jl")

Main.faux

In [ ]:
const getAttr = faux.getAttr

In [46]:
include("../../code/julia/eos_create.jl")

create_cube (generic function with 6 methods)

In [47]:
openfiles = HDF5fd.filesDict()


Main.HDF5fd.filesDict(Dict{Any,Any}(), 0)

In [48]:
include("../../code/julia/eos_rastwrite_lines.jl")

Main.rastwrite_lines

* https://github.com/lbusett/prismaread/blob/master/R/pr_convert.R

In [49]:

f="data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5"
in_file = HDF5fd.open(openfiles,f,"r")




HDF5 data file: data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5

In [ ]:
vnir_wl_mat = faux.getData(in_file, "//KDP_AUX/Cw_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse? 
vnir_fwhm_mat = faux.getData(in_file, "KDP_AUX/Fwhm_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?

swir_wl_mat = faux.getData(in_file, "//KDP_AUX/Cw_Swir_Matrix")
swir_fwhm_mat = faux.getData(in_file, "//KDP_AUX/Fwhm_Swir_Matrix")

In [ ]:
vnir_wl_mat

In [ ]:
@btime vnir_wl_mat_nonfun = vnir_wl_mat[(vnir_wl_mat[:,1].!=0),:]

In [ ]:
@btime swir_fun_nonz = faux.matCrop(vnir_wl_mat)

In [ ]:
cvnir_wl = faux.matCrop(vnir_wl_mat)

In [ ]:

cswir_wl = faux.matCrop(swir_wl_mat)

In [ ]:
first = 0
last = 0
for i in 1:256
    if vnir_fwhm_mat[i,1]!=0
        last = i
        if first ==0
            first = i
        end        
    end    
end
@show last 
@show first
last - first

In [ ]:
size(vnir_wl_mat)

In [ ]:
first = 0
last = 0
for i in 1:256
    if swir_wl_mat[i,1]!=0
        last = i
        if first ==0
            first = i
        end        
    end    
end
@show last 
@show first
last - first

In [ ]:
c = zeros(Int,3,3)
c[1,2]=12
c[2,1]=21
c

In [ ]:
a = zeros(Int,3,3)
b = ones(Int,3,3)
vcat(a,b)

In [ ]:
closeall(openfiles)

In [ ]:
faux.filename(in_file.filename)

In [ ]:
include("../../code/julia/faux.jl")

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9]
c=[a...,b...]

In [ ]:
c=vcat(a,b)

In [ ]:
using CSV
using DataFrames
using LinearAlgebra
using DataFramesMeta
#=mkpath("downloads")
download("https://github.com/sfacca/stage-Machine-learning/raw/master/extdata/md_indexes_list.txt","downloads/indexes_list.txt")
=#
index_list = CSV.read("downloads/indexes_list.txt")
select!(index_list, Not(:id))

av_indexes= select(index_list, [:Name,:Formula])
indexes = ["ARI","BGI","BRI"]
sel_indexes = filter(row -> row.Name ∈ indexes, av_indexes)
av_indexes


In [ ]:
# get additional metadata
    sunzen  = hdfeos.getAttr(file, "Sun_zenith_angle")
    sunaz  = hdfeos.getAttr(file, "Sun_azimuth_angle")
    acqtime  = hdfeos.getAttr(file, "Product_StartTime")

ang_df = DataFrame(date = acqtime),sunzen = sunzen,sunaz = sunaz)
CSV.write("out/ang_df.ang",ang_df,delim=' ',quotechar='"',quotestrings=true)

In [ ]:
req_wls = sort(unique(vcat(extractWvl.(av_indexes[:Formula])...)))

In [ ]:
wl_vnir = rand(Float64,66)
#1 prendiamo elem req_wls >= maximum(wl_vnir)
sel_vnir = filter(item -> item <= maximum(wl_vnir) && item != 0,req_wls)

In [ ]:
myArr = [1,4,5,2,0]
minimum(filter(item -> item !=0,myArr))

In [ ]:
y = unique(sort(b))

In [ ]:
checkCommon(usa,usb)

In [ ]:
using ArchGDAL

In [ ]:
wl_vnir

In [ ]:
x = [1,2,3]
y= 2
@show z = x.-y
@show za = abs.(x.-y)


In [ ]:
function closestWvl(wvl::Array{Int64,1},x::Int64)
  y = abs.(wvl.-x)
  #lapply(selbands_vnir, FUN = function(x) which.min(abs(wl_vnir - x))))
  minimum(abs.(wvl.-x))
end
function closestWvlFun(wvl::Array{Int64,1})
  (x)->(minimum(abs.(wvl.-x)))
end

*http://www.johnmyleswhite.com/notebook/2012/04/09/comparing-julia-and-rs-vocabularies/

In [ ]:
using DataFrames
c = [1,2,3]
b=[4,56,6]
d=DataFrame("parola parola"=c,"ta ta"= b)

In [ ]:
?round

In [ ]:
c = [0.1234567,1.123456789,2.1234567890]
round.(c,digits=3)

In [ ]:
c=[12345,123456]
round.(c/1000000,digits=5)

In [ ]:
df = DataFrame(asd=[1,2],bcd=[3,4])
rename!(df,["as d","dd a"])

In [ ]:
?names!

In [ ]:
?CSV.write

In [ ]:
using HDF5
HDF5.exists(file,"//KDP_AUX/Cw_Vnir_Matrix")

In [ ]:
getAttr(file, "Start_index_EO_VNIR")

In [ ]:
function getAttr2(file, name::String)    
    read(attrs(file), name)
end

In [ ]:
x = "ciao"
if !isnothing(x)
    println("ok")
end

In [ ]:
 A = rand([0, 1], 10,5)
length(A[:,1])

In [ ]:
B = A[4:10,:]

In [ ]:
B[ordA,:]

In [ ]:
x = 7^2
a = [1:x...]

In [ ]:
mA = reshape(a,7,7)


In [ ]:
mA = mA[2:4,:]

In [ ]:
tA = mA[:,mA[1,:].>15]

In [ ]:
ordA =mA[:,ord]

In [ ]:
ordA[2,2]=0
ordA

In [ ]:
ordA = ordA[:,(ordA[1,:] .!=0)]

In [ ]:
vnir_start = 3
vnir_stop = 45
swir_start = 8
swir_stop = 47

vnir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_wl_mat = vnir_wl_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_wl_mat = vnir_wl_mat[:,order_vnir]#ordino righe secondo order_vnir
vnir_wl_mat = vnir_wl_mat[:,(vnir_wl_mat[1,:].!=0)]#tolgo colonne che inzian con 0
#stessa cosa per vnir fwhm
vnir_fwhm_mat = faux.getData(file, "KDP_AUX/Fwhm_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_fwhm_mat = vnir_fwhm_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_fwhm_mat = vnir_fwhm_mat[:,order_vnir]#ordino colonne secondo order_vnir
vnir_fwhm_mat = vnir_fwhm_mat[:,(vnir_fwhm_mat[1,:].!=0)]#tolgo colonne con i dove [1,i]==0
#stessa cosa per swir
swir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Swir_Matrix")
swir_wl_mat = swir_wl_mat[swir_start:swir_stop,:]
#swir_wl_mat = swir_wl_mat[:,order_swir]
swir_wl_mat = swir_wl_mat[:,(swir_wl_mat[1,:].!=0)]
swir_fwhm_mat = faux.getData(file, "//KDP_AUX/Fwhm_Swir_Matrix")
swir_fwhm_mat = swir_fwhm_mat[swir_start:swir_stop,:]
#swir_fwhm_mat = swir_fwhm_mat[:,order_swir]
swir_fwhm_mat = swir_fwhm_mat[:,(swir_fwhm_mat[1,:].!=0)]

In [ ]:
swir_fwhm_mat

In [ ]:
ordA

In [ ]:
mA

In [ ]:
[ordA mA]

In [ ]:
length(mA)

In [ ]:
typeof(mA)

In [ ]:
length(mA[1,:])

In [ ]:

vnir_cube = faux.getData(file,string("HDFEOS/SWATHS/PRS_L2D_","HRC","/Data Fields/VNIR_Cube"))

In [ ]:
using SparseArrays

In [ ]:
a= false
b=true
c=true
if a
    if b
        println()
    end
else
    println("else of a")
end

In [ ]:
sat = [-3:3...]

In [ ]:
x = [1:10...]
typeof(join(x,"b"))

In [ ]:
x.+"b"

In [ ]:
s = string.(x).*"b"

In [ ]:
using DataFrames
?rename!

In [ ]:
?replace

In [ ]:
?replace

In [ ]:
x = 12
y = 1.1
@show supertype(typeof(x))
supertype(typeof(y))

In [ ]:
isa(x, Number)

In [ ]:
using CSV


In [ ]:
?CSV.write

In [ ]:
round(4/3,digits=0)

In [ ]:
x = Array{}(undef,3,3)

In [ ]:
?Array

In [ ]:
zeros(3,3)

In [ ]:
?zeros

In [ ]:
?replace

In [ ]:
a = [1,2,3,4]
reshape(a,2,2)

In [ ]:
a = 1:6
Array((1:5).')

In [ ]:
reshape!(a,2,2)

In [ ]:
using ArchGDAL

In [ ]:
?ArchGDAL.write!

In [ ]:
s = "ASDF"
titlecase(s)

In [ ]:
cube = faux.getData(f,"HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/SWIR_Cube")
size(cube)

In [ ]:
length(size(cube))

In [87]:
include("../../code/julia/hdfeos.jl")
include("../../code/julia/faux.jl")
include("../../code/julia/eos_rastwrite_lines.jl")

Main.rastwrite_lines

In [51]:
using ArchGDAL
using CSV
using DataFrames
#test scritt rast_full con priorità vnir

In [52]:
bandvnir = CSV.read("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_VNIR.wvl")
bandswir = CSV.read("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_SWIR.wvl")


171×4 DataFrame
│ Row │ band  │ orband │ wl      │ fwhm    │
│     │ Int64 │ Int64  │ Float64 │ Float64 │
├─────┼───────┼────────┼─────────┼─────────┤
│ 1   │ 1     │ 3      │ 942.913 │ 10.918  │
│ 2   │ 2     │ 4      │ 950.967 │ 10.9559 │
│ 3   │ 3     │ 5      │ 959.471 │ 12.0313 │
│ 4   │ 4     │ 6      │ 969.338 │ 12.1034 │
│ 5   │ 5     │ 7      │ 978.683 │ 12.2177 │
│ 6   │ 6     │ 8      │ 988.354 │ 12.345  │
│ 7   │ 7     │ 9      │ 998.314 │ 12.6989 │
│ 8   │ 8     │ 10     │ 1008.11 │ 12.4385 │
│ 9   │ 9     │ 11     │ 1017.92 │ 12.9587 │
│ 10  │ 10    │ 12     │ 1028.75 │ 13.052  │
⋮
│ 161 │ 161   │ 163    │ 2428.37 │ 9.44328 │
│ 162 │ 162   │ 164    │ 2435.3  │ 9.37404 │
│ 163 │ 163   │ 165    │ 2442.16 │ 8.76996 │
│ 164 │ 164   │ 166    │ 2448.9  │ 9.40947 │
│ 165 │ 165   │ 167    │ 2456.3  │ 9.43895 │
│ 166 │ 166   │ 168    │ 2462.79 │ 8.8837  │
│ 167 │ 167   │ 169    │ 2469.39 │ 9.12707 │
│ 168 │ 168   │ 170    │ 2476.76 │ 9.66423 │
│ 169 │ 169   │ 171    │ 2483.57 │ 8.96724 │
│ 170 │ 170   │ 172    │ 2490.01 │ 9.01312 │
│ 171 │ 171   │ 173    │ 2496.85 │ 9.50537 │

In [57]:
maxvnir = bandvnir[end,:]
bandstoget = bandswir[end-1,:]

DataFrameRow
│ Row │ band  │ orband │ wl      │ fwhm    │
│     │ Int64 │ Int64  │ Float64 │ Float64 │
├─────┼───────┼────────┼─────────┼─────────┤
│ 170 │ 170   │ 172    │ 2490.01 │ 9.01312 │

In [64]:
index=size(bandswir)[1]
for i = 1:size(bandswir)[1]
    if bandswir[i,:].wl > maxvnir.wl
        index = i
        break
    end
end
swir_copied = bandswir[index:end,:]
vnir_copied = bandvnir
#index#

230×4 DataFrame
│ Row │ band  │ orband │ wl      │ fwhm    │
│     │ Int64 │ Int64  │ Float64 │ Float64 │
├─────┼───────┼────────┼─────────┼─────────┤
│ 1   │ 1     │ 4      │ 402.307 │ 11.4216 │
│ 2   │ 2     │ 5      │ 411.187 │ 10.5781 │
│ 3   │ 3     │ 6      │ 419.255 │ 9.8455  │
│ 4   │ 4     │ 7      │ 426.855 │ 9.41124 │
│ 5   │ 5     │ 8      │ 434.198 │ 9.25446 │
│ 6   │ 6     │ 9      │ 441.548 │ 9.22298 │
│ 7   │ 7     │ 10     │ 448.923 │ 9.1489  │
│ 8   │ 8     │ 11     │ 456.267 │ 9.08349 │
│ 9   │ 9     │ 12     │ 463.619 │ 8.9641  │
│ 10  │ 10    │ 13     │ 470.837 │ 8.96158 │
⋮
│ 220 │ 161   │ 163    │ 2428.37 │ 9.44328 │
│ 221 │ 162   │ 164    │ 2435.3  │ 9.37404 │
│ 222 │ 163   │ 165    │ 2442.16 │ 8.76996 │
│ 223 │ 164   │ 166    │ 2448.9  │ 9.40947 │
│ 224 │ 165   │ 167    │ 2456.3  │ 9.43895 │
│ 225 │ 166   │ 168    │ 2462.79 │ 8.8837  │
│ 226 │ 167   │ 169    │ 2469.39 │ 9.12707 │
│ 227 │ 168   │ 170    │ 2476.76 │ 9.66423 │
│ 228 │ 169   │ 171    │ 2483.57 │ 8.96724 │
│ 229 │ 170   │ 172    │ 2490.01 │ 9.01312 │
│ 230 │ 171   │ 173    │ 2496.85 │ 9.50537 │

In [70]:
swir_copied[:type]="SWIR"
vnir_copied[:type]="VNIR"
total_wls = vcat(vnir_copied,swir_copied)
total_wls[:band]=1:230


230×5 DataFrame
│ Row │ band  │ orband │ wl      │ fwhm    │ type   │
│     │ Int64 │ Int64  │ Float64 │ Float64 │ String │
├─────┼───────┼────────┼─────────┼─────────┼────────┤
│ 1   │ 1     │ 4      │ 402.307 │ 11.4216 │ VNIR   │
│ 2   │ 2     │ 5      │ 411.187 │ 10.5781 │ VNIR   │
│ 3   │ 3     │ 6      │ 419.255 │ 9.8455  │ VNIR   │
│ 4   │ 4     │ 7      │ 426.855 │ 9.41124 │ VNIR   │
│ 5   │ 5     │ 8      │ 434.198 │ 9.25446 │ VNIR   │
│ 6   │ 6     │ 9      │ 441.548 │ 9.22298 │ VNIR   │
│ 7   │ 7     │ 10     │ 448.923 │ 9.1489  │ VNIR   │
│ 8   │ 8     │ 11     │ 456.267 │ 9.08349 │ VNIR   │
│ 9   │ 9     │ 12     │ 463.619 │ 8.9641  │ VNIR   │
│ 10  │ 10    │ 13     │ 470.837 │ 8.96158 │ VNIR   │
⋮
│ 220 │ 220   │ 163    │ 2428.37 │ 9.44328 │ SWIR   │
│ 221 │ 221   │ 164    │ 2435.3  │ 9.37404 │ SWIR   │
│ 222 │ 222   │ 165    │ 2442.16 │ 8.76996 │ SWIR   │
│ 223 │ 223   │ 166    │ 2448.9  │ 9.40947 │ SWIR   │
│ 224 │ 224   │ 167    │ 2456.3  │ 9.43895 │ SWIR   │
│ 225 │ 225   │ 168    │ 2462.79 │ 8.8837  │ SWIR   │
│ 226 │ 226   │ 169    │ 2469.39 │ 9.12707 │ SWIR   │
│ 227 │ 227   │ 170    │ 2476.76 │ 9.66423 │ SWIR   │
│ 228 │ 228   │ 171    │ 2483.57 │ 8.96724 │ SWIR   │
│ 229 │ 229   │ 172    │ 2490.01 │ 9.01312 │ SWIR   │
│ 230 │ 230   │ 173    │ 2496.85 │ 9.50537 │ SWIR   │

In [88]:
swir_cube = nothing
gtf=nothing
crs=nothing
vnir_cube = nothing

ArchGDAL.read("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_SWIR.tif") do dataset
    global swir_cube = faux.getCube(dataset,index)#prendo swir solo da 
    global gtf = ArchGDAL.getgeotransform(dataset)
    global crs = ArchGDAL.getproj(dataset)
end
ArchGDAL.read("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_VNIR.tif") do dataset
    global vnir_cube = faux.getCube(dataset)#prendo tutto vnir
end
@show size(vnir_cube)[3]
@show size(swir_cube)[3]
size(vnir_cube)[3] + size(swir_cube)[3]

reading bands 5 to 171 , this might take a while...
finished reading bands
reading bands 1 to 63 , this might take a while...
finished reading bands
(size(vnir_cube))[3] = 63
(size(swir_cube))[3] = 167


230

In [89]:
cube = cat(vnir_cube,swir_cube,dims=3)

1235×1209×230 Array{UInt16,3}:
[:, :, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x000

In [102]:
notcube = nothing

In [103]:
ccc = cat(notcube, swir_cube, dims = 3)

LoadError: DimensionMismatch("mismatch in dimension 1 (expected 1 got 1235)")

In [90]:
size(vnir_cube)

(1235, 1209, 63)

In [92]:
size(swir_cube)
out_file_full = "out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_FULL.tif"

"out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_FULL.tif"

In [93]:
rastwrite_lines.write(cube,
        out_file_full,
        gtf,
        crs
        )

preparing to write tiff
writing bands in  empty tiff
finished writing bands
setting geotransform
setting crs string
finished writing on out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_FULL.tif.tif


In [98]:
problems = Array{String,1}(undef,0)

String[]

In [101]:
push!(problems, "ciao")

2-element Array{String,1}:
 "ciao"
 "ciao"

In [95]:
CSV.write("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_FULL.wvl",total_wls)

"out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_FULL.wvl"

In [94]:
?CSV.write

```
CSV.write(file, table; kwargs...) => file
table |> CSV.write(file; kwargs...) => file
```

Write a [Tables.jl interface input](https://github.com/JuliaData/Tables.jl) to a csv file, given as an `IO` argument or `String`/FilePaths.jl type representing the file name to write to. Alternatively, `CSV.RowWriter` creates a row iterator, producing a csv-formatted string for each row in an input table.

Supported keyword arguments include:

  * `delim::Union{Char, String}=','`: a character or string to print out as the file's delimiter
  * `quotechar::Char='"'`: ascii character to use for quoting text fields that may contain delimiters or newlines
  * `openquotechar::Char`: instead of `quotechar`, use `openquotechar` and `closequotechar` to support different starting and ending quote characters
  * `escapechar::Char='"'`: ascii character used to escape quote characters in a text field
  * `missingstring::String=""`: string to print for `missing` values
  * `dateformat=Dates.default_format(T)`: the date format string to use for printing out `Date` & `DateTime` columns
  * `append=false`: whether to append writing to an existing file/IO, if `true`, it will not write column names by default
  * `writeheader=!append`: whether to write an initial row of delimited column names, not written by default if appending
  * `header`: pass a list of column names (Symbols or Strings) to use instead of the column names of the input table
  * `newline='\n'`: character or string to use to separate rows (lines in the csv file)
  * `quotestrings=false`: whether to force all strings to be quoted or not
  * `decimal='.'`: character to use as the decimal point when writing floating point numbers
  * `transform=(col,val)->val`: a function that is applied to every cell e.g. we can transform all `nothing` values to `missing` using `(col, val) -> something(val, missing)`
  * `bom=false`: whether to write a UTF-8 BOM header (0xEF 0xBB 0xBF) or not


In [ ]:
swir_raster = ArchGDAL.readraster("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_SWIR.tif")
#append di bande > index



In [33]:
include("../../code/julia/faux.jl")

Main.faux

In [30]:
using ArchGDAL
using BenchmarkTools

In [34]:
ArchGDAL.read("out/PRS_L2D_STD_20200627102334_20200627102339_0001.he5_VNIR.tif") do ds
    ds = ds
    @time faux.getCube(ds)
end

  3.655812 seconds (126.51 k allocations: 5.963 GiB, 14.55% gc time)


1235×1209×63 Array{UInt16,3}:
[:, :, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000

In [24]:
typeof(dataset)

ArchGDAL.RasterDataset{UInt16,ArchGDAL.IDataset}

In [35]:
band = ArchGDAL.getband(dataset,2)
typeof(band)

ArchGDAL.IRasterBand{UInt16}

In [21]:
@btime ArchGDAL.read(ArchGDAL.getband(dataset,2))

  425.000 μs (5 allocations: 2.85 MiB)


1235×1209 Array{UInt16,2}:
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x000

In [39]:
bands= Array{Any,1}(undef, 7)

7-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [41]:
bands= Array{ArchGDAL.IRasterBand, 1}(undef, 7)

7-element Array{ArchGDAL.IRasterBand,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef