In [30]:
#include("../../code/julia/hdfeos_convert.jl")
include("../../code/julia/hdf5 tree.jl")
include("../../code/julia/HDF5filesDict.jl")
include("../../code/julia/printHDF.jl")
include("../../code/julia/drawTree.jl")
closeall = HDF5fd.closeall

closeall (generic function with 1 method)

In [31]:
include("../../code/julia/hdfeos.jl")

Main.hdfeos

In [40]:
include("../../code/julia/faux.jl")
const getAttr = faux.getAttr

Main.faux

In [113]:
include("../../code/julia/eos_create.jl")

Main.eos_create

In [34]:
openfiles = HDF5fd.filesDict()


Main.HDF5fd.filesDict(Dict{Any,Any}(), 0)

* https://github.com/lbusett/prismaread/blob/master/R/pr_convert.R

In [37]:

f="data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5"
in_file = HDF5fd.open(openfiles,f,"r")




HDF5 data file: data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5

In [45]:

#setup
proc_lev = getAttr(in_file, "Processing_Level")
wl_vnir = getAttr(in_file, "List_Cw_Vnir")
wl_swir = getAttr(in_file, "List_Cw_Swir")
fwhm_vnir = getAttr(in_file, "List_Fwhm_Vnir")
fwhm_swir = getAttr(in_file, "List_Fwhm_Swir")
# get additional metadata
sunzen  = getAttr(in_file, "Sun_zenith_angle")
sunaz  = getAttr(in_file, "Sun_azimuth_angle")
acqtime  = getAttr(in_file, "Product_StartTime")

# riordinazioni
order_vnir = sortperm(wl_vnir)# permut
wl_vnir = wl_vnir[order_vnir]    
order_swir = sortperm(wl_swir)
wl_swir = wl_swir[order_swir]      
fwhm_vnir = fwhm_vnir[order_vnir]    
fwhm_swir = fwhm_swir[order_swir]
# join
fwhms = vcat(fwhm_vnir, fwhm_swir)
wls = vcat(wl_vnir, wl_swir);

In [109]:
eos_create.create_cube(in_file,proc_lev,"HCO","out/prove_create_2",wl_vnir,order_vnir,fwhm_vnir)

####### create_cube start #########
eos_create_VNIR
processing level: 2D
prendo cubo da HDF5 data file: data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5 HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/VNIR_Cube
prendo vnir
no selbands, prendo tutto
Band: 1 not present
Band: 2 not present
Band: 3 not present
Importing Band: 4 (402.30698) of: 1:66
first band is cube
Importing Band: 5 (411.18665) of: 1:66
appending band to cube
cube has (1235, 1209, 2) dims
Importing Band: 6 (419.25522) of: 1:66
appending band to cube
cube has (1235, 1209, 3) dims
Importing Band: 7 (426.85532) of: 1:66
appending band to cube
cube has (1235, 1209, 4) dims
Importing Band: 8 (434.19843) of: 1:66
appending band to cube
cube has (1235, 1209, 5) dims
Importing Band: 9 (441.5481) of: 1:66
appending band to cube
cube has (1235, 1209, 6) dims
Importing Band: 10 (448.92273) of: 1:66
appending band to cube
cube has (1235, 1209, 7) dims
Importing Band: 11 (456.2667) of: 1:66
appending band to cube
cube has (1235, 1209, 

In [115]:
eos_create.create_cube(in_file,proc_lev,"HCO","out/prove_create_2",wl_swir,order_swir,fwhm_swir,"SWIR")

####### create_cube start #########
eos_create_SWIR
processing level: 2D
prendo cubo da HDF5 data file: data/PRS_L2D_STD_20200627102334_20200627102339_0001.he5 HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/SWIR_Cube
prendo swir
no selbands, prendo tutto
Band: 1 not present
Band: 2 not present
Importing Band: 3 (942.9125) of: 1:173
Importing Band: 4 (950.9671) of: 1:173
Importing Band: 5 (959.4708) of: 1:173
Importing Band: 6 (969.3384) of: 1:173
Importing Band: 7 (978.68256) of: 1:173
Importing Band: 8 (988.3542) of: 1:173
Importing Band: 9 (998.3145) of: 1:173
Importing Band: 10 (1008.11426) of: 1:173
Importing Band: 11 (1017.92206) of: 1:173
Importing Band: 12 (1028.7452) of: 1:173
Importing Band: 13 (1037.7394) of: 1:173
Importing Band: 14 (1047.4034) of: 1:173
Importing Band: 15 (1057.3585) of: 1:173
Importing Band: 16 (1067.589) of: 1:173
Importing Band: 17 (1078.019) of: 1:173
Importing Band: 18 (1088.5704) of: 1:173
Importing Band: 19 (1099.0891) of: 1:173
Importing Band: 20 (1109.724) 

finished writing on out/prove_create_2_SWIR.tif
creating and writing dataframe of selected bands with wavelengths and bandwidths
####### create_cube end #########


In [ ]:
#=
(
        f,
        proc_lev,
        source,#string ["HC0" | "HRC"], Considered Data Cub
        out_file,
        wl,#NB: ORDERED wl = raw_wvl[order]
        order,
        fwhm,#NB: riordinate con ordine order
        ERR_MATRIX=nothing,
        type="VNIR",
        apply_errmatrix=false,
        selbands = NULL,
        in_L2_file = NULL
        )#string = [ VNIR , SWIR ]
=#

In [112]:
?eos_create.create_cube

No documentation found.

`Main.eos_create.create_cube` is a `Function`.

```
# 6 methods for generic function "create_cube":
[1] create_cube(f, proc_lev, source, out_file, wl, order, fwhm) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
[2] create_cube(f, proc_lev, source, out_file, wl, order, fwhm, ERR_MATRIX) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
[3] create_cube(f, proc_lev, source, out_file, wl, order, fwhm, ERR_MATRIX, type) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
[4] create_cube(f, proc_lev, source, out_file, wl, order, fwhm, ERR_MATRIX, type, apply_errmatrix) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
[5] create_cube(f, proc_lev, source, out_file, wl, order, fwhm, ERR_MATRIX, type, apply_errmatrix, selbands) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
[6] create_cube(f, proc_lev, source, out_file, wl, order, fwhm, ERR_MATRIX, type, apply_errmatrix, selbands, in_L2_file) in Main.eos_create at C:\Users\i am\Documents\GitHub\stage-Machine-learning\code\julia\eos_create.jl:20
```


In [36]:
closeall(openfiles)

chiuso 1 file


In [101]:
res = []

Any[]

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9]
c=[a...,b...]

In [ ]:
c=vcat(a,b)

In [ ]:
function tryIf(x)
    if x in [1,2,3,"asd",false]
        println("$x ok")
        else 
        println("$x non ok")
    end
    
end

In [ ]:
x = "ciao"
tryIf(1)
tryIf("asd")
tryIf("kmkgnmg")

In [ ]:
using CSV
using DataFrames
mkpath("downloads/")
download("https://github.com/sfacca/stage-Machine-learning/raw/master/extdata/md_indexes_list.txt","downloads/indexes_list.txt")
index_list = CSV.read("downloads/indexes_list.txt")

select!(index_list, Not(:id))
names(index_list)

In [ ]:
index_list[:Formula]

In [ ]:
using CSV
using DataFrames
using LinearAlgebra
using DataFramesMeta
#=mkpath("downloads")
download("https://github.com/sfacca/stage-Machine-learning/raw/master/extdata/md_indexes_list.txt","downloads/indexes_list.txt")
=#
index_list = CSV.read("downloads/indexes_list.txt")
select!(index_list, Not(:id))

av_indexes= select(index_list, [:Name,:Formula])
indexes = ["ARI","BGI","BRI"]
sel_indexes = filter(row -> row.Name ∈ indexes, av_indexes)
av_indexes


In [ ]:
# get additional metadata
    sunzen  = hdfeos.getAttr(file, "Sun_zenith_angle")
    sunaz  = hdfeos.getAttr(file, "Sun_azimuth_angle")
    acqtime  = hdfeos.getAttr(file, "Product_StartTime")

ang_df = DataFrame(date = acqtime),sunzen = sunzen,sunaz = sunaz)
CSV.write("out/ang_df.ang",ang_df,delim=' ',quotechar='"',quotestrings=true)

In [ ]:
string("asd","fgh","_asd")

In [ ]:
function extractWvl(str::String)#prende stringa, ritorna array di numeri
  currnum = 0
  res::Array{Int,1} = []
  intc = ['1','2','3','4','5','6','7','8','9','0']
  afterR = false
  for char in str
    if afterR
      if char in intc
        currnum = currnum*10
        currnum = currnum + parse(Int,char)             
                
      else
        push!(res,currnum)
        currnum=0
        afterR = false
      end    
    end
    if char == 'R'
      afterR = true
    end
  end
  push!(res,currnum)  
  res
end

In [ ]:
req_wls = sort(unique(vcat(extractWvl.(av_indexes[:Formula])...)))

In [ ]:
wl_vnir = rand(Float64,66)
#1 prendiamo elem req_wls >= maximum(wl_vnir)
sel_vnir = filter(item -> item <= maximum(wl_vnir) && item != 0,req_wls)

In [ ]:
myArr = [1,4,5,2,0]
minimum(filter(item -> item !=0,myArr))

In [ ]:
a = [6,6,9,12,4,2,6]
b= [9,87,6,87,33]
x = unique(sort(a))


In [ ]:
y = unique(sort(b))

In [ ]:
checkCommon(usa,usb)

In [ ]:
using ArchGDAL

In [ ]:
wl_vnir

In [ ]:
x = [1,2,3]
y= 2
@show z = x.-y
@show za = abs.(x.-y)


In [ ]:
function closestWvl(wvl::Array{Int64,1},x::Int64)
  y = abs.(wvl.-x)
  #lapply(selbands_vnir, FUN = function(x) which.min(abs(wl_vnir - x))))
  minimum(abs.(wvl.-x))
end
function closestWvlFun(wvl::Array{Int64,1})
  (x)->(minimum(abs.(wvl.-x)))
end

In [ ]:
wvl = [4,3,6,1,-5,1,2,5,6,1]
x = [5,-8,4,1,4,7,8]
closestWvlFun(wvl).(x)

In [ ]:
wl_vnir[5]=0
wl_vnir[12]=0

seqbands_vnir = [1:66...]
  for i in 1:66
    if wl_vnir[i]==0
      seqbands_vnir[i]=0      
    end
  end
seqbands_vnir = filter(x->x!=0,seqbands_vnir)

In [ ]:
seqbands_vnir = [1:66]

In [ ]:
wl_vnir = wl_vnir[seqbands_vnir]

*http://www.johnmyleswhite.com/notebook/2012/04/09/comparing-julia-and-rs-vocabularies/

In [ ]:
using DataFrames
c = [1,2,3]
b=[4,56,6]
d=DataFrame("parola parola"=c,"ta ta"= b)

In [ ]:
?round

In [ ]:
c = [0.1234567,1.123456789,2.1234567890]
round.(c,digits=3)

In [ ]:
c=[12345,123456]
round.(c/1000000,digits=5)

In [ ]:
df = DataFrame(asd=[1,2],bcd=[3,4])
rename!(df,["as d","dd a"])

In [ ]:
?names!

In [ ]:
?CSV.write

In [ ]:
using HDF5
HDF5.exists(file,"//KDP_AUX/Cw_Vnir_Matrix")

In [ ]:
getAttr(file, "Start_index_EO_VNIR")

In [ ]:
function getAttr2(file, name::String)    
    read(attrs(file), name)
end

In [ ]:
x = "ciao"
if !isnothing(x)
    println("ok")
end

In [19]:
 A = rand([0, 1], 10,5)
length(A[:,1])

10

In [ ]:
B = A[4:10,:]

In [ ]:
B[ordA,:]

In [ ]:
x = 7^2
a = [1:x...]

In [ ]:
mA = reshape(a,7,7)


In [ ]:
mA = mA[2:4,:]

In [ ]:
tA = mA[:,mA[1,:].>15]

In [ ]:
ordA =mA[:,ord]

In [ ]:
ordA[2,2]=0
ordA

In [ ]:
ordA = ordA[:,(ordA[1,:] .!=0)]

In [ ]:
vnir_start = 3
vnir_stop = 45
swir_start = 8
swir_stop = 47

vnir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_wl_mat = vnir_wl_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_wl_mat = vnir_wl_mat[:,order_vnir]#ordino righe secondo order_vnir
vnir_wl_mat = vnir_wl_mat[:,(vnir_wl_mat[1,:].!=0)]#tolgo colonne che inzian con 0
#stessa cosa per vnir fwhm
vnir_fwhm_mat = faux.getData(file, "KDP_AUX/Fwhm_Vnir_Matrix")#prendo matrice intera NB: molti 0, sparse?
vnir_fwhm_mat = vnir_fwhm_mat[vnir_start:vnir_stop,:]# solo righe vnir
#vnir_fwhm_mat = vnir_fwhm_mat[:,order_vnir]#ordino colonne secondo order_vnir
vnir_fwhm_mat = vnir_fwhm_mat[:,(vnir_fwhm_mat[1,:].!=0)]#tolgo colonne con i dove [1,i]==0
#stessa cosa per swir
swir_wl_mat = faux.getData(file, "//KDP_AUX/Cw_Swir_Matrix")
swir_wl_mat = swir_wl_mat[swir_start:swir_stop,:]
#swir_wl_mat = swir_wl_mat[:,order_swir]
swir_wl_mat = swir_wl_mat[:,(swir_wl_mat[1,:].!=0)]
swir_fwhm_mat = faux.getData(file, "//KDP_AUX/Fwhm_Swir_Matrix")
swir_fwhm_mat = swir_fwhm_mat[swir_start:swir_stop,:]
#swir_fwhm_mat = swir_fwhm_mat[:,order_swir]
swir_fwhm_mat = swir_fwhm_mat[:,(swir_fwhm_mat[1,:].!=0)]

In [ ]:
swir_fwhm_mat

In [ ]:
ordA

In [ ]:
mA

In [ ]:
[ordA mA]

In [ ]:
length(mA)

In [ ]:
typeof(mA)

In [ ]:
length(mA[1,:])

In [ ]:

vnir_cube = faux.getData(file,string("HDFEOS/SWATHS/PRS_L2D_","HRC","/Data Fields/VNIR_Cube"))

In [ ]:
C = sparse(faux.getData(file,"/HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/VNIR_Cube"))

In [ ]:
using SparseArrays

In [1]:
a= false
b=true
c=true
if a
    if b
        println()
    end
else
    println("else of a")
end

else of a


In [2]:
sat = [-3:3...]

7-element Array{Int64,1}:
 -3
 -2
 -1
  0
  1
  2
  3

In [8]:
x = [1:10...]
typeof(join(x,"b"))

String

In [9]:
x.+"b"

LoadError: MethodError: no method matching +(::Int64, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:86
  +(::Integer, !Matched::Integer) at int.jl:918
  ...

In [12]:
s = string.(x).*"b"

10-element Array{String,1}:
 "1b"
 "2b"
 "3b"
 "4b"
 "5b"
 "6b"
 "7b"
 "8b"
 "9b"
 "10b"

In [14]:
using DataFrames
?rename!

LoadError: syntax: invalid identifier name "?"

In [16]:
?replace

search: replace replace! redisplay



```
replace(A, old_new::Pair...; [count::Integer])
```

Return a copy of collection `A` where, for each pair `old=>new` in `old_new`, all occurrences of `old` are replaced by `new`. Equality is determined using [`isequal`](@ref). If `count` is specified, then replace at most `count` occurrences in total.

The element type of the result is chosen using promotion (see [`promote_type`](@ref)) based on the element type of `A` and on the types of the `new` values in pairs. If `count` is omitted and the element type of `A` is a `Union`, the element type of the result will not include singleton types which are replaced with values of a different type: for example, `Union{T,Missing}` will become `T` if `missing` is replaced.

See also [`replace!`](@ref).

# Examples

```jldoctest
julia> replace([1, 2, 1, 3], 1=>0, 2=>4, count=2)
4-element Array{Int64,1}:
 0
 4
 1
 3

julia> replace([1, missing], missing=>0)
2-element Array{Int64,1}:
 1
 0
```

---

```
replace(new::Function, A; [count::Integer])
```

Return a copy of `A` where each value `x` in `A` is replaced by `new(x)`. If `count` is specified, then replace at most `count` values in total (replacements being defined as `new(x) !== x`).

# Examples

```jldoctest
julia> replace(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])
4-element Array{Int64,1}:
 2
 2
 6
 4

julia> replace(Dict(1=>2, 3=>4)) do kv
           first(kv) < 3 ? first(kv)=>3 : kv
       end
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 3
```

---

```
replace(s::AbstractString, pat=>r; [count::Integer])
```

Search for the given pattern `pat` in `s`, and replace each occurrence with `r`. If `count` is provided, replace at most `count` occurrences. `pat` may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring (when `pat` is a `Regex` or `AbstractString`) or character (when `pat` is an `AbstractChar` or a collection of `AbstractChar`). If `pat` is a regular expression and `r` is a [`SubstitutionString`](@ref), then capture group references in `r` are replaced with the corresponding matched text. To remove instances of `pat` from `string`, set `r` to the empty `String` (`""`).

# Examples

```jldoctest
julia> replace("Python is a programming language.", "Python" => "Julia")
"Julia is a programming language."

julia> replace("The quick foxes run quickly.", "quick" => "slow", count=1)
"The slow foxes run quickly."

julia> replace("The quick foxes run quickly.", "quick" => "", count=1)
"The  foxes run quickly."

julia> replace("The quick foxes run quickly.", r"fox(es)?" => s"bus\1")
"The quick buses run quickly."
```


In [1]:
?replace

search: replace replace! redisplay



```
replace(A, old_new::Pair...; [count::Integer])
```

Return a copy of collection `A` where, for each pair `old=>new` in `old_new`, all occurrences of `old` are replaced by `new`. Equality is determined using [`isequal`](@ref). If `count` is specified, then replace at most `count` occurrences in total.

The element type of the result is chosen using promotion (see [`promote_type`](@ref)) based on the element type of `A` and on the types of the `new` values in pairs. If `count` is omitted and the element type of `A` is a `Union`, the element type of the result will not include singleton types which are replaced with values of a different type: for example, `Union{T,Missing}` will become `T` if `missing` is replaced.

See also [`replace!`](@ref).

# Examples

```jldoctest
julia> replace([1, 2, 1, 3], 1=>0, 2=>4, count=2)
4-element Array{Int64,1}:
 0
 4
 1
 3

julia> replace([1, missing], missing=>0)
2-element Array{Int64,1}:
 1
 0
```

---

```
replace(new::Function, A; [count::Integer])
```

Return a copy of `A` where each value `x` in `A` is replaced by `new(x)`. If `count` is specified, then replace at most `count` values in total (replacements being defined as `new(x) !== x`).

# Examples

```jldoctest
julia> replace(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])
4-element Array{Int64,1}:
 2
 2
 6
 4

julia> replace(Dict(1=>2, 3=>4)) do kv
           first(kv) < 3 ? first(kv)=>3 : kv
       end
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 3
```

---

```
replace(s::AbstractString, pat=>r; [count::Integer])
```

Search for the given pattern `pat` in `s`, and replace each occurrence with `r`. If `count` is provided, replace at most `count` occurrences. `pat` may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring (when `pat` is a `Regex` or `AbstractString`) or character (when `pat` is an `AbstractChar` or a collection of `AbstractChar`). If `pat` is a regular expression and `r` is a [`SubstitutionString`](@ref), then capture group references in `r` are replaced with the corresponding matched text. To remove instances of `pat` from `string`, set `r` to the empty `String` (`""`).

# Examples

```jldoctest
julia> replace("Python is a programming language.", "Python" => "Julia")
"Julia is a programming language."

julia> replace("The quick foxes run quickly.", "quick" => "slow", count=1)
"The slow foxes run quickly."

julia> replace("The quick foxes run quickly.", "quick" => "", count=1)
"The  foxes run quickly."

julia> replace("The quick foxes run quickly.", r"fox(es)?" => s"bus\1")
"The quick buses run quickly."
```


In [4]:
x = 12
y = 1.1
@show supertype(typeof(x))
supertype(typeof(y))

supertype(typeof(x)) = Signed


AbstractFloat

In [5]:
isa(x, Number)

true

In [7]:
using CSV


In [8]:
?CSV.write

```
CSV.write(file, table; kwargs...) => file
table |> CSV.write(file; kwargs...) => file
```

Write a [Tables.jl interface input](https://github.com/JuliaData/Tables.jl) to a csv file, given as an `IO` argument or `String`/FilePaths.jl type representing the file name to write to. Alternatively, `CSV.RowWriter` creates a row iterator, producing a csv-formatted string for each row in an input table.

Supported keyword arguments include:

  * `delim::Union{Char, String}=','`: a character or string to print out as the file's delimiter
  * `quotechar::Char='"'`: ascii character to use for quoting text fields that may contain delimiters or newlines
  * `openquotechar::Char`: instead of `quotechar`, use `openquotechar` and `closequotechar` to support different starting and ending quote characters
  * `escapechar::Char='"'`: ascii character used to escape quote characters in a text field
  * `missingstring::String=""`: string to print for `missing` values
  * `dateformat=Dates.default_format(T)`: the date format string to use for printing out `Date` & `DateTime` columns
  * `append=false`: whether to append writing to an existing file/IO, if `true`, it will not write column names by default
  * `writeheader=!append`: whether to write an initial row of delimited column names, not written by default if appending
  * `header`: pass a list of column names (Symbols or Strings) to use instead of the column names of the input table
  * `newline='\n'`: character or string to use to separate rows (lines in the csv file)
  * `quotestrings=false`: whether to force all strings to be quoted or not
  * `decimal='.'`: character to use as the decimal point when writing floating point numbers
  * `transform=(col,val)->val`: a function that is applied to every cell e.g. we can transform all `nothing` values to `missing` using `(col, val) -> something(val, missing)`
  * `bom=false`: whether to write a UTF-8 BOM header (0xEF 0xBB 0xBF) or not


In [20]:
round(4/3,digits=0)

1.0

In [6]:
x = Array{}(undef,3,3)

LoadError: MethodError: no method matching Array(::UndefInitializer, ::Int64, ::Int64)
Closest candidates are:
  Array(!Matched::LinearAlgebra.UniformScaling, ::Integer, ::Integer) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\uniformscaling.jl:438

In [2]:
?Array

search: Array SubArray BitArray DenseArray StridedArray PermutedDimsArray



```
Array{T,N} <: AbstractArray{T,N}
```

`N`-dimensional dense array with elements of type `T`.

---

```
Array{T}(undef, dims)
Array{T,N}(undef, dims)
```

Construct an uninitialized `N`-dimensional [`Array`](@ref) containing elements of type `T`. `N` can either be supplied explicitly, as in `Array{T,N}(undef, dims)`, or be determined by the length or number of `dims`. `dims` may be a tuple or a series of integer arguments corresponding to the lengths in each dimension. If the rank `N` is supplied explicitly, then it must match the length or number of `dims`. See [`undef`](@ref).

# Examples

```julia-repl
julia> A = Array{Float64,2}(undef, 2, 3) # N given explicitly
2×3 Array{Float64,2}:
 6.90198e-310  6.90198e-310  6.90198e-310
 6.90198e-310  6.90198e-310  0.0

julia> B = Array{Float64}(undef, 2) # N determined by the input
2-element Array{Float64,1}:
 1.87103e-320
 0.0
```

---

```
Array{T}(nothing, dims)
Array{T,N}(nothing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Array{Union{Nothing, String}}(nothing, 2)
2-element Array{Union{Nothing, String},1}:
 nothing
 nothing

julia> Array{Union{Nothing, Int}}(nothing, 2, 3)
2×3 Array{Union{Nothing, Int64},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing
```

---

```
Array{T}(missing, dims)
Array{T,N}(missing, dims)
```

Construct an `N`-dimensional [`Array`](@ref) containing elements of type `T`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Array{Union{Missing, String}}(missing, 2)
2-element Array{Union{Missing, String},1}:
 missing
 missing

julia> Array{Union{Missing, Int}}(missing, 2, 3)
2×3 Array{Union{Missing, Int64},2}:
 missing  missing  missing
 missing  missing  missing
```


In [7]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [8]:
?zeros

search: zeros count_zeros set_zero_subnormals get_zero_subnormals leading_zeros



```
zeros([T=Float64,] dims::Tuple)
zeros([T=Float64,] dims...)
```

Create an `Array`, with element type `T`, of all zeros with size specified by `dims`. See also [`fill`](@ref), [`ones`](@ref).

# Examples

```jldoctest
julia> zeros(1)
1-element Array{Float64,1}:
 0.0

julia> zeros(Int8, 2, 3)
2×3 Array{Int8,2}:
 0  0  0
 0  0  0
```


In [9]:
?replace

search: replace replace! redisplay



```
replace(A, old_new::Pair...; [count::Integer])
```

Return a copy of collection `A` where, for each pair `old=>new` in `old_new`, all occurrences of `old` are replaced by `new`. Equality is determined using [`isequal`](@ref). If `count` is specified, then replace at most `count` occurrences in total.

The element type of the result is chosen using promotion (see [`promote_type`](@ref)) based on the element type of `A` and on the types of the `new` values in pairs. If `count` is omitted and the element type of `A` is a `Union`, the element type of the result will not include singleton types which are replaced with values of a different type: for example, `Union{T,Missing}` will become `T` if `missing` is replaced.

See also [`replace!`](@ref).

# Examples

```jldoctest
julia> replace([1, 2, 1, 3], 1=>0, 2=>4, count=2)
4-element Array{Int64,1}:
 0
 4
 1
 3

julia> replace([1, missing], missing=>0)
2-element Array{Int64,1}:
 1
 0
```

---

```
replace(new::Function, A; [count::Integer])
```

Return a copy of `A` where each value `x` in `A` is replaced by `new(x)`. If `count` is specified, then replace at most `count` values in total (replacements being defined as `new(x) !== x`).

# Examples

```jldoctest
julia> replace(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])
4-element Array{Int64,1}:
 2
 2
 6
 4

julia> replace(Dict(1=>2, 3=>4)) do kv
           first(kv) < 3 ? first(kv)=>3 : kv
       end
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 3
```

---

```
replace(s::AbstractString, pat=>r; [count::Integer])
```

Search for the given pattern `pat` in `s`, and replace each occurrence with `r`. If `count` is provided, replace at most `count` occurrences. `pat` may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring (when `pat` is a `Regex` or `AbstractString`) or character (when `pat` is an `AbstractChar` or a collection of `AbstractChar`). If `pat` is a regular expression and `r` is a [`SubstitutionString`](@ref), then capture group references in `r` are replaced with the corresponding matched text. To remove instances of `pat` from `string`, set `r` to the empty `String` (`""`).

# Examples

```jldoctest
julia> replace("Python is a programming language.", "Python" => "Julia")
"Julia is a programming language."

julia> replace("The quick foxes run quickly.", "quick" => "slow", count=1)
"The slow foxes run quickly."

julia> replace("The quick foxes run quickly.", "quick" => "", count=1)
"The  foxes run quickly."

julia> replace("The quick foxes run quickly.", r"fox(es)?" => s"bus\1")
"The quick buses run quickly."
```


In [11]:
a = [1,2,3,4]
reshape(a,2,2)

2×2 Array{Int64,2}:
 1  3
 2  4

In [4]:
a = 1:6
Array((1:5).')

LoadError: syntax: the ".'" operator is discontinued

In [13]:
reshape!(a,2,2)

LoadError: UndefVarError: reshape! not defined

In [1]:
using ArchGDAL

In [2]:
?ArchGDAL.write!

No documentation found.

`ArchGDAL.write!` is a `Function`.

```
# 9 methods for generic function "write!":
[1] write!(rb::ArchGDAL.AbstractRasterBand, buffer::Array{var"#s93",2} where var"#s93"<:Real) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:174
[2] write!(rb::ArchGDAL.AbstractRasterBand, buffer::Array{var"#s93",2} where var"#s93"<:Real, xoffset::Integer, yoffset::Integer, xsize::Integer, ysize::Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:179
[3] write!(rb::ArchGDAL.AbstractRasterBand, buffer::Array{var"#s93",2} where var"#s93"<:Real, rows::UnitRange{var"#s92"} where var"#s92"<:Integer, cols::UnitRange{var"#s91"} where var"#s91"<:Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:191
[4] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",2} where var"#s93"<:Real, i::Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:337
[5] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",3} where var"#s93"<:Real, indices) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:342
[6] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",2} where var"#s93"<:Real, i::Integer, xoffset::Integer, yoffset::Integer, xsize::Integer, ysize::Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:351
[7] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",3} where var"#s93"<:Real, indices, xoffset::Integer, yoffset::Integer, xsize::Integer, ysize::Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:364
[8] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",2} where var"#s93"<:Real, i::Integer, rows::UnitRange{var"#s92"} where var"#s92"<:Integer, cols::UnitRange{var"#s91"} where var"#s91"<:Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:378
[9] write!(dataset::ArchGDAL.AbstractDataset, buffer::Array{var"#s93",3} where var"#s93"<:Real, indices, rows::UnitRange{var"#s92"} where var"#s92"<:Integer, cols::UnitRange{var"#s91"} where var"#s91"<:Integer) in ArchGDAL at C:\Users\i am\.julia\packages\ArchGDAL\4s5Fq\src\raster\rasterio.jl:389
```


In [35]:
s = "ASDF"
titlecase(s)

"Asdf"

In [36]:
cube = faux.getData(f,"HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/SWIR_Cube")
size(cube)

(1235, 173, 1209)

In [38]:
length(size(cube))

3

In [40]:
type = "AaAa"
titlecase(type)

"Aaaa"

In [42]:
uppercase(type)

"AAAA"

In [6]:
c = zeros(Int, 3,3,3)

3×3×3 Array{Int64,3}:
[:, :, 1] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 2] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 3] =
 0  0  0
 0  0  0
 0  0  0

In [15]:
b = ones(Int,3,3)

3×3 Array{Int64,2}:
 1  1  1
 1  1  1
 1  1  1

In [12]:
push!(c[:][:],b...)

36-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [16]:
c = [c;b]

LoadError: DimensionMismatch("mismatch in dimension 3 (expected 3 got 1)")

In [20]:
c = cat(c,b,dims=3)

3×3×4 Array{Int64,3}:
[:, :, 1] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 2] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 3] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 4] =
 1  1  1
 1  1  1
 1  1  1

In [21]:
rename!(c,["a","b","c"])

LoadError: UndefVarError: rename! not defined

In [23]:
?rename!

search: propertynames

Couldn't find rename!
Perhaps you meant read!, replace!, resize!, names or read


No documentation found.

Binding `rename!` does not exist.


In [29]:
# eos create testing
include("../../code/julia/eos_create.jl")

Main.eos_create

In [77]:
c = zeros(Int,150,150)

150×150 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

In [78]:
b = c

150×150 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

In [80]:
b = cat(b,c,dims=3)

150×150×2 Array{Int64,3}:
[:, :, 1] =
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0