# algrebra lineare

+ https://github.com/JuliaAcademy/DataScience/blob/master/02.%20Linear%20Algebra.ipynb

In [1]:
using LinearAlgebra

In [15]:
using SparseArrays
using Images
using MAT

┌ Info: Precompiling MAT [23992714-dd62-5051-b70f-ba57cb901cac]
└ @ Base loading.jl:1278


In [3]:
using Pkg

In [6]:
Pkg.add("MAT")

  Resolving package versions...
  Installed CodecZlib ────────── v0.7.0
  Installed BufferedStreams ──── v1.0.0
  Installed TranscodingStreams ─ v0.9.5
  Installed MAT ──────────────── v0.8.1
Updating `C:\Users\i am\.julia\environments\v1.5\Project.toml`
  [23992714] + MAT v0.8.1
Updating `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`
  [e1450e63] + BufferedStreams v1.0.0
  [944b1d66] + CodecZlib v0.7.0
  [23992714] + MAT v0.8.1
  [3bb67fe8] + TranscodingStreams v0.9.5


In [8]:
# poichè matrici son salvate in mem come array, meglio iterare su colonne rispetto che righe
A = rand(10,10); # created a random matrix of size 10-by-10
Atranspose = A' # matrix transpose
A = A*Atranspose; # matrix multiplication
@show A[11] == A[1,2];
#A[1:10] è prima riga, A[12] è quindi prima riga seconda colonnna

A[11] == A[1, 2] = true


In [12]:
@show typeof(Atranspose)
sizeof(Atranspose)
# transpose non traspone veramente, tiene adjoint

typeof(Atranspose) = Adjoint{Float64,Array{Float64,2}}


8

In [11]:
sizeof(A)

800

In [13]:
#poicè adjoint, possiamo risalire alla matrice non transposa facilmente
Atranspose.parent

10×10 Array{Float64,2}:
 0.389487   0.196072  0.709937   0.206778  …  0.240629  0.165792   0.0767833
 0.440177   0.19682   0.858638   0.637242     0.515248  0.404306   0.502825
 0.50565    0.250091  0.141698   0.717208     0.887062  0.31445    0.900004
 0.0838596  0.424433  0.644828   0.779603     0.529695  0.449297   0.408935
 0.263764   0.704174  0.179648   0.976396     0.548318  0.983519   0.874577
 0.59169    0.398763  0.433366   0.850075  …  0.532752  0.284996   0.53182
 0.807232   0.285439  0.763267   0.906554     0.922842  0.406043   0.0141546
 0.0685355  0.448376  0.207981   0.761472     0.441878  0.316889   0.450097
 0.376372   0.147398  0.0625099  0.488454     0.605325  0.0823693  0.728467
 0.403602   0.877347  0.755292   0.716056     0.712594  0.192642   0.572092

In [14]:
#per ottenere vera trasposta possiamo usare copy
B = copy(Atranspose)

10×10 Array{Float64,2}:
 0.389487   0.440177  0.50565   0.0838596  …  0.0685355  0.376372   0.403602
 0.196072   0.19682   0.250091  0.424433      0.448376   0.147398   0.877347
 0.709937   0.858638  0.141698  0.644828      0.207981   0.0625099  0.755292
 0.206778   0.637242  0.717208  0.779603      0.761472   0.488454   0.716056
 0.425918   0.476219  0.592198  0.744769      0.793497   0.861691   0.589166
 0.866402   0.101093  0.84172   0.621916   …  0.49429    0.741216   0.152206
 0.696113   0.924686  0.682494  0.550386      0.794563   0.129061   0.31417
 0.240629   0.515248  0.887062  0.529695      0.441878   0.605325   0.712594
 0.165792   0.404306  0.31445   0.449297      0.316889   0.0823693  0.192642
 0.0767833  0.502825  0.900004  0.408935      0.450097   0.728467   0.572092

In [16]:
# già visto risolutore sistemi lineare \ in intro a julia

## fattorizzazione


In [19]:
# lu fact L*U=P
luA = lu(A)


LU{Float64,Array{Float64,2}}
L factor:
10×10 Array{Float64,2}:
 1.0        0.0        0.0       …  0.0       0.0        0.0       0.0
 0.813173   1.0        0.0          0.0       0.0        0.0       0.0
 0.878935   0.469007   1.0          0.0       0.0        0.0       0.0
 0.999211   0.68459    0.911582     0.0       0.0        0.0       0.0
 0.863045  -0.386239  -0.666228     0.0       0.0        0.0       0.0
 0.734418   0.885059   0.445318  …  0.0       0.0        0.0       0.0
 0.715993   0.881775   0.402028     1.0       0.0        0.0       0.0
 0.742955   0.500082   0.441927     0.844983  1.0        0.0       0.0
 0.628654   0.113715   0.845488     0.400765  0.305277   1.0       0.0
 0.848653   0.419333   0.154133     0.928166  0.487122  -0.353411  1.0
U factor:
10×10 Array{Float64,2}:
 2.60105  2.83031   3.45542    …  2.61126      2.58592     3.03746
 0.0      0.848124  0.0755823     0.403521    -0.227072    0.304359
 0.0      0.0       1.00091       0.562966     0.860751   

In [21]:
# qr fact
qrA = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.32864    0.612321     0.421279   …   0.309589   -0.13904     0.0460866
 -0.309649  -0.412812     0.454977      -0.192405   -0.103072    0.173485
 -0.334691  -0.00218777  -0.463103       0.153765    0.586109    0.193784
 -0.32316    0.0222082    0.128316      -0.0130668   0.432761   -0.580881
 -0.380491  -0.112356    -0.306274       0.176955   -0.0940895   0.0665067
 -0.27966   -0.359703     0.0813661  …  -0.0572175  -0.160764   -0.551886
 -0.380791   0.384732     0.096985      -0.279575    0.0359467   0.117094
 -0.282911  -0.0770541   -0.0601427     -0.640338   -0.0214944   0.34563
 -0.239386   0.159344    -0.509024      -0.0303083  -0.620134   -0.20529
 -0.272644  -0.364409     0.109719       0.565349   -0.134983    0.329375
R factor:
10×10 Array{Float64,2}:
 -6.83066  -8.61356  -10.2545    …  -8.55452    -7.5573     -8.83029
  0.0      -1.16875   -0.819949    

In [22]:
?factorize

search: factorize Factorization factorial



```
factorize(A)
```

Compute a convenient factorization of `A`, based upon the type of the input matrix. `factorize` checks `A` to see if it is symmetric/triangular/etc. if `A` is passed as a generic matrix. `factorize` checks every element of `A` to verify/rule out each property. It will short-circuit as soon as it can rule out symmetry/triangular structure. The return value can be reused for efficient solving of multiple systems. For example: `A=factorize(A); x=A\b; y=A\C`.

| Properties of `A`          | type of factorization                      |
|:-------------------------- |:------------------------------------------ |
| Positive-definite          | Cholesky (see [`cholesky`](@ref))          |
| Dense Symmetric/Hermitian  | Bunch-Kaufman (see [`bunchkaufman`](@ref)) |
| Sparse Symmetric/Hermitian | LDLt (see [`ldlt`](@ref))                  |
| Triangular                 | Triangular                                 |
| Diagonal                   | Diagonal                                   |
| Bidiagonal                 | Bidiagonal                                 |
| Tridiagonal                | LU (see [`lu`](@ref))                      |
| Symmetric real tridiagonal | LDLt (see [`ldlt`](@ref))                  |
| General square             | LU (see [`lu`](@ref))                      |
| General non-square         | QR (see [`qr`](@ref))                      |

If `factorize` is called on a Hermitian positive-definite matrix, for instance, then `factorize` will return a Cholesky factorization.

# Examples

```jldoctest
julia> A = Array(Bidiagonal(fill(1.0, (5, 5)), :U))
5×5 Array{Float64,2}:
 1.0  1.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  0.0
 0.0  0.0  0.0  1.0  1.0
 0.0  0.0  0.0  0.0  1.0

julia> factorize(A) # factorize will check to see that A is already factorized
5×5 Bidiagonal{Float64,Array{Float64,1}}:
 1.0  1.0   ⋅    ⋅    ⋅
  ⋅   1.0  1.0   ⋅    ⋅
  ⋅    ⋅   1.0  1.0   ⋅
  ⋅    ⋅    ⋅   1.0  1.0
  ⋅    ⋅    ⋅    ⋅   1.0
```

This returns a `5×5 Bidiagonal{Float64}`, which can now be passed to other linear algebra functions (e.g. eigensolvers) which will use specialized methods for `Bidiagonal` types.


In [28]:
# sparse matrix
# matrice contenente, per la stratrange maggioranza di comb colonna/riga, 0
# storata compressa
using SparseArrays
S = sprand(5,5,2/5)

5×5 SparseMatrixCSC{Float64,Int64} with 10 stored entries:
  [1, 1]  =  0.546534
  [3, 1]  =  0.133458
  [5, 1]  =  0.987296
  [2, 2]  =  0.864348
  [5, 2]  =  0.831911
  [3, 3]  =  0.935003
  [5, 4]  =  0.353319
  [1, 5]  =  0.185174
  [2, 5]  =  0.410785
  [5, 5]  =  0.610866

In [29]:
S

5×5 SparseMatrixCSC{Float64,Int64} with 10 stored entries:
  [1, 1]  =  0.546534
  [3, 1]  =  0.133458
  [5, 1]  =  0.987296
  [2, 2]  =  0.864348
  [5, 2]  =  0.831911
  [3, 3]  =  0.935003
  [5, 4]  =  0.353319
  [1, 5]  =  0.185174
  [2, 5]  =  0.410785
  [5, 5]  =  0.610866

In [30]:
Matrix(S)

5×5 Array{Float64,2}:
 0.546534  0.0       0.0       0.0       0.185174
 0.0       0.864348  0.0       0.0       0.410785
 0.133458  0.0       0.935003  0.0       0.0
 0.0       0.0       0.0       0.0       0.0
 0.987296  0.831911  0.0       0.353319  0.610866

In [31]:
S.rowval

10-element Array{Int64,1}:
 1
 3
 5
 2
 5
 3
 5
 1
 2
 5

In [35]:
S.colptr
#colptr indica dove iniziano le colonne
# eg, se S.colptr[2]=3, allora la seconda colonna inizia dal secondo elemento

6-element Array{Int64,1}:
  1
  4
  6
  7
  8
 11

In [36]:
S.nzval
# qua ci sono i valori effettivi

10-element Array{Float64,1}:
 0.5465342750341036
 0.13345824692476138
 0.9872961907663786
 0.8643477698976827
 0.8319111344612424
 0.9350032414744565
 0.3533188011997015
 0.18517389748700586
 0.4107853850468641
 0.6108655667797533