# Julia Academy - Introduction to Julia

si può vedere documentazione di funzioni e keyword antecedendo con ?

In [113]:
?+

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


in jupyter, un ; alla fine dell ultima linea rimuove output

In [27]:
a = 13

13

In [28]:
a = 13;

## 1 installazione

vedi tutorial installazione Julia

## 2 varibiles and printing
println() stampa input a schermata
variabili non sono fortemente tipate di default

In [2]:
asd = "ciao"
println(asd)
asd = 12
println(asd)

ciao
12


In [6]:
function foo()
           x::Int8 = 100
           x = "stringa"
end
foo()

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int8
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

## 3 string
dichiarabili tra "  (singole) o tra """ (triple)
dichiarando tra """ è poi possibile includere " come caratteri all interno della stringa come definita"

si possono inserire valori variabili o espressioni con $()

op tra/con string: 
concatenazione di 2 styringe con *
concatenaz di stringa con se stessa n volte con ^n


In [11]:
string1 = "ciao"
string2 = """ ciao "ciao" """
string3 = mystring^3
string4 = "questo è un numero: $(12+3) queste sono stringe: $(string1*string2)"
println("string1: "*string1*" string2: "*string2*" string3: "*string3*" striing4: "*string4)

string1: ciao string2:  ciao "ciao"  string3: ciaociaociao striing4: questo è un numero: 15 queste sono stringe: ciao ciao "ciao" 


## 4 strutture dati
3 tipi di collection principali: tuple, array, dictionaries

### tuple
ordinate, immutabili

In [14]:
tupla = ("uno","due",3)

("uno", "due", 3)

### array
ordinato, mutabile, bisogna reallocarlo per aumentarlo di dimensioni

array di n elem -> indici da 1 a n

In [2]:
myarr = [1,2,3]
myarr[1]=2
myarr

3-element Array{Int64,1}:
 2
 2
 3

In [3]:
myarr[4]=123 #genera errore

LoadError: BoundsError: attempt to access 3-element Array{Int64,1} at index [4]

julia gestisce array di tipi misti se e solo se l array è inizializzato con tipi diversi, altrimenti tenta di convertire:

In [6]:
mixarr=["cane",1.3, 1.5]
mixarr[3]=33
mixarr

3-element Array{Any,1}:
   "cane"
  1.3
 33

In [8]:
wrongarr = [1.5,2.5,3.5]
wrongarr[1]=1
wrongarr[2]="string"
wrongarr

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

pop!(array) rimuove ultimo elemento e lo ritorna

per convenzione, funzioni che modificano l'input terminano in !

In [13]:
myarr = [1,2,3,4]
println("array prima: $myarr")
println("elemento rimosso: $(pop!(myarr))")
println("array dopo: $myarr")

array prima: [1, 2, 3, 4]
elemento rimosso: 4
array dopo: [1, 2, 3]


### dizionari
non ordinati, mutabili, struttura di coppie  chiave/valore

In [14]:
mydict = Dict("mordenkeinen" => "fr", "elminst" => "gh") #inizializzazione
mydict["iggwilv"] = "gh" #aggiunta coppia
mydict["elminst"] #ritorna valore assegnato alla chiave cercata

"gh"

## 5 cicli for/while
funzionano come dappertutto

sintassi:

In [17]:
for i in 1:10
    println(i)
end #end chiude blocco for

1
2
3
4
5
6
7
8
9
10


In [19]:
i = 0
while i <10
    i = i+1
    println(i)
end

1
2
3
4
5
6
7
8
9
10


zucchero sintattico: for innestato, comodo per matrici

In [20]:
n = 4
Matrice = fill(0, (n,n))
for i in 1:n, j in 1:n
    Matrice[i,j]=i+j
end
Matrice

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

## 6 condizionali
sintassi


In [29]:
condizione = 1==1
if condizione
    println("vera")
else
    println("falsa")
end

vera


condizione ternaria a?b:c

In [30]:
condizione ? println("vera") : println("falsa")

vera


 $ \wedge $ logico

In [31]:
secondacondizione = 1 == 2
condizione&&secondacondizione

false

NB: le condizioni sono valutate/eseguite in ordine:

In [32]:
condizione&&println("questo stampa")
secondacondizione&&println("questo no");

questo stampa


## 7 funzioni

definite mediante keyword function

In [37]:
function foo(x)
    x^2
end
function sayhi(name)
    println("o hi $name")
end

sayhi (generic function with 1 method)

In [59]:
println("3^2= $(foo(3)) ")
sayhi("mark")

3^2= 9 
o hi mark


definite in riga singola senza kword

In [39]:
foo2(x) = x^2

foo2 (generic function with 1 method)

definite come funzioni landa

In [40]:
foo3 = x-> x^2

#1 (generic function with 1 method)

In [41]:
foo3(2)

4

per convenzione, funzioni terminanti in ! mutano l'input, funzioni senza ! non mutano l input, eg:

In [42]:
v = [3, 5, 2]
sort(v)

3-element Array{Int64,1}:
 2
 3
 5

In [43]:
v

3-element Array{Int64,1}:
 3
 5
 2

In [44]:
sort!(v)

3-element Array{Int64,1}:
 2
 3
 5

In [45]:
v

3-element Array{Int64,1}:
 2
 3
 5

funzioni di ordine superiore prendon funzioni come input

eg, map(function,struct) applica la funzione di input a ogni membro della struct

In [46]:
map(foo, [1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

### broadcast
broadcast è funzione generalizzata di map, può esser invocata con sintassi:

{funzione da invocare sugli elem}.( {struct degli elementi} )

riproponendo esempio di prima:

In [48]:
foo.([1,2,3])

3-element Array{Int64,1}:
 1
 4
 9

### overload
possiamo fare overload di una funzione dandogli altri metodi per combinazioni di tipi di input diverse:

In [58]:
foo(x)=x^2
foo(s::String)=" è una stringa"
println("2^2 = $(foo(2))")
asd = "asd"
println("e invece questa $(foo(asd)) ")

2^2 = 4
e invece questa  è una stringa 


In [ ]:
julia manda errore in caso di input ambigui (ovvero quando più metodi sono definiti per quella combinazione di input)

possiamo overloadare anche operatori:

In [70]:
"stringa " + "stringa"

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::PyObject, ::Any) at C:\Users\i am\.julia\packages\PyCall\zqDXB\src\pyoperators.jl:13
  +(::Any, !Matched::PyObject) at C:\Users\i am\.julia\packages\PyCall\zqDXB\src\pyoperators.jl:14

In [71]:
import Base: +
+(x::String,y::String) = x*y
"stringa " + "stringa"

"stringastringa"

## 8 pacchetti
prima di poter installare pacchetti bisogna importare Pkg:
using Pkg

sintassi installazione pacchetto:

Pkg.add("{nome pacc}")

prima di usarlo:

include {nome pacc}

NB: nomi case sensitive 

## 9 plotting

pacchetti base per plotting:

In [49]:
using Pkg
Pkg.add("Plots")
Pkg.add("PlotlyJS")
Pkg.add("ORCA")

   Updating registry at `C:\Users\i am\.julia\registries\General`
  Resolving package versions...
No Changes to `C:\Users\i am\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`
  Resolving package versions...
No Changes to `C:\Users\i am\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`
  Resolving package versions...
No Changes to `C:\Users\i am\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`


In [114]:
using Plots
x = -3:0.1:3
f(x) = x^2
y = f.(x) #applica f() ad ogni elemento di x, come visto prima

gr() #backend grafico

plot(x,y, legend=false) #crea linea tra punti x,y
scatter!(x,y) #crea punti x,y

SystemError: SystemError: opening file "C:\\Users\\IAM~1\\AppData\\Local\\Temp\\jl_nB9WaKpXie.svg": No such file or directory

NB: scatter!() aggiunge un scatterplot al plot antecedente, scatter() creerebbe un nuovo plot con solo scatter

## 10 benchmarking
package BenchmarkTools ha strumenti base di benchmar

In [63]:
using Pkg
Pkg.add("BenchmarkTools")
Pkg.add("PyCall") #serve per lanciare python da julia

  Resolving package versions...
No Changes to `C:\Users\i am\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`


In [66]:
using BenchmarkTools

a = rand(10^7) # a è array di 10^7 ~N(0,1)
d = Dict()
using PyCall
pysum = pybuiltin("sum")
pysum(a)
py_list_bench = @benchmark $pysum($a)
d["Python built-in"] = minimum(py_list_bench.times) / 1e6

py"""
def py_sum(A):
    s = 0.0
    for a in A:
        s += a
    return s
"""

sum_py = py"py_sum"
py_hand_bench = @benchmark $sum_py($a)
d["Python handmade"] = minimum(py_hand_bench) / 1e6

j_bench = @benchmark sum($a)
d["Julia built-in"] = minimum(j_bench.times) / 1e6
d

LoadError: MethodError: no method matching /(::BenchmarkTools.TrialEstimate, ::Float64)
Closest candidates are:
  /(!Matched::BigFloat, ::Union{Float16, Float32, Float64}) at mpfr.jl:437
  /(!Matched::Float64, ::Float64) at float.jl:407
  /(!Matched::Missing, ::Number) at missing.jl:115
  ...

# 11 algebra di base
iniziamo creando una matrice A, e un vettore x

In [72]:
x = ones(3)
A = rand(1:4,3,3)

3×3 Array{Int64,2}:
 2  4  3
 2  1  4
 4  2  1

operatore * ha metodi per la moltiplicazione matrice * vettore

In [73]:
b = A*x

3-element Array{Float64,1}:
 9.0
 7.0
 7.0

possiamo ottenere trasposta coniugata con ' , trasposta con transpose()


In [75]:
conjtrA = A'
transpA = transpose(A)
display(transpA)
display(conjtrA)
display(A)

3×3 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 2  2  4
 4  1  2
 3  4  1

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 2  2  4
 4  1  2
 3  4  1

3×3 Array{Int64,2}:
 2  4  3
 2  1  4
 4  2  1

### risoluzione sistemi lineari
sistemi lineari del tipo Ax=b possono essere risolti facilmente

per A quadrata, Ax=b si risolve come


In [76]:
A\b

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

se la matrice ha più righe che colonne, riceveremo soluzione per quadrati minimi 

In [77]:
Atall = rand(3, 2)
Atall\b

2-element Array{Float64,1}:
 8.540488961501845
 9.48670556911429

quando il rango non è sufficiente, avremo soluzione a norma minima di quadrati minimi

In [78]:
v = rand(3)
rankdef = hcat(v, v)
rankdef\b

2-element Array{Float64,1}:
 5.25354568275248
 5.253545682752481

lo stesso avremo quando la matrice ha più colonne che righe

In [79]:
bshort = rand(2)
Ashort = rand(2, 3)
Ashort\bshort

3-element Array{Float64,1}:
 0.05165194747737656
 0.4345923961588576
 0.4851460682377696

## 12 fattorizzazioni/scomposizioni, autovalori/autovettori, attributi di dati

usando package LinearAlgebra si può svolgere fattorizzazione LU tramite fun lu(A), ritorna matrici l,u vettore di permutazione p

In [82]:
using LinearAlgebra
A = rand(3, 3)
x = fill(1, (3,))
b = A * x
l,u,p = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.441722  1.0       0.0
 0.858667  0.360977  1.0
U factor:
3×3 Array{Float64,2}:
 0.416257  0.0321873  0.242309
 0.0       0.241418   0.258553
 0.0       0.0        0.399609

julia permette di salvare anche tutto in una variabile di tipo speciale

In [85]:
Alu = lu(A)
typeof(Alu)

LU{Float64,Array{Float64,2}}

si può poi accedere ai vari elem con punto

In [86]:
Alu.P

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  0.0  1.0
 0.0  1.0  0.0

possiamo usare le fattorizzazioni nei metodi

ad esempio possiamo risolvere il sistema lineare precedente con la fattorizzata:

In [89]:
Alu\b == A\b

true

possiamo anche trovare il determinante

In [90]:
det(Alu) == det(A)

true

julia svolge fattorizzazioni QR in maniera simile

In [91]:
Aqr = qr(A)
Aqr.Q

3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.719363   0.424943    0.54949
 -0.617694  -0.0294635  -0.785867
 -0.317759  -0.90474     0.28368

### decomposizione spettrale (eigendecomposition)
risultati di decomposiz spettrale vengono salvati in tipi `Factorization`

In [92]:
Asym = A + A'
AsymEig = eigen(Asym)
typeof(AsymEig)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}

autovalori/autovettori posson essere indicizzat da questo tipo cosi:

In [93]:
AsymEig.values
AsymEig.vectors

3×3 Array{Float64,2}:
  0.0408753   0.860321  0.508112
 -0.798246   -0.277739  0.534475
  0.600942   -0.427445  0.675395

poichè la fattorizzazione è salvata in un tipo particolare, avverrà il dispatch del metodo più adatto quando la useremo, utilizzando quindi le sue proprietà algebriche

### struct e attributi speciali per matrici
perquanto Julia possa individuare strutture utili e particolari delle matrici, è sempre meglio esplicitarle

In [95]:
n = 1000
A = randn(n,n)
Asym = A + A'
issymmetric(Asym)

true

come detto, Julia può riconosciere la simmetria di una matrice, proviamo adesso la stessa cosa con una matrice a cui aggiungiamo degli errori

In [96]:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps() #simulazione di avere dei minuscoli errori nei dati
issymmetric(Asym_noisy)

false

In [100]:
5eps()

1.1102230246251565e-15

vediamo che julia non vede più la matrice essere praticamente simmetrica

possiamo però dirgli esplicitamente che lo è:

In [102]:
Asym_explicit = Symmetric(Asym_noisy);
issymmetric(Asym_explicit)

true

vediamo ora come una accortezza di questo tipo possa aumentasre notevolmente la performance con un piccolo benchmark:

In [103]:
using BenchmarkTools
benchsym = @benchmark eigvals(Asym)
benchnoisy = @benchmark eigvals(Asym_noisy)
benchexplicit = @benchmark eigvals(Asym_explicit);

In [138]:
Pkg.add("UnicodePlots")
using Plots
unicodeplots()


names = ["matrice simmetrica", "matrice con \epsilon ", "matrice esplicitata simmetrica"]
values = [median(benchsym.times/ 1e6), median(benchnoisy.times/ 1e6), median(benchexplicit.times/ 1e6)]
names = [1,2,3]
values=[1,2,3]
Plots.bar(names,values, legend=false)

  Resolving package versions...
No Changes to `C:\Users\i am\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\i am\.julia\environments\v1.5\Manifest.toml`


         +------------------------------------------------------------+ 
    3.09 |                                        .,---------------   | 
         |                                     .r/`|              |   | 
         |                                  .r/`   |              |   | 
         |                               _r/`      |              |   | 
         |                            _-"          |              |   | 
         |                         _-"             |              |   | 
         |                     ._r=____________.   |              |   | 
         |                  ../`|              |   |              |   | 
         |               ../`   |              |   |              |   | 
         |            ../`      |              |   |              |   | 
         |         ../`         |              |   |              |   | 
         |      ../`            |              |   |              |   | 
         |   ../`               |              |   